@extends('admin.crbt.base')

@section('page_title', 'Daily CRBT MIS Report')
@section('report_title', 'Daily CRBT Activities Summary')

@section('report_content')
<!-- Filter Section -->
<div class="row g-3 mb-4">
    <div class="col-md-4">
        <input type="date" id="startDate" class="form-control" placeholder="Start date">
    </div>
    <div class="col-md-4">
        <input type="date" id="endDate" class="form-control" placeholder="End date">
    </div>
    <div class="col-md-4 d-grid">
        <button id="applyFilter" class="btn btn-primary">Apply Filter</button>
    </div>
</div>

<!-- Summary Cards -->
<div class="row g-4 mb-4">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h6 class="text-muted mb-3">New Subscribers</h6>
                <h3 class="f-w-300 d-flex align-items-center m-b-0" id="totalSubscriptions">
                    <i class="feather icon-user-plus text-primary f-24 m-r-5"></i>
                    <span>Loading...</span>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h6 class="text-muted mb-3">Total Unsubscriptions</h6>
                <h3 class="f-w-300 d-flex align-items-center m-b-0" id="totalUnsubscriptions">
                    <i class="feather icon-user-minus text-danger f-24 m-r-5"></i>
                    <span>Loading...</span>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h6 class="text-muted mb-3">Active Subscribers</h6>
                <h3 class="f-w-300 d-flex align-items-center m-b-0" id="activeSubscribers">
                    <i class="feather icon-users text-success f-24 m-r-5"></i>
                    <span>Loading...</span>
                </h3>
            </div>
        </div>
    </div>
</div>

<!-- Charts Section -->
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5>Subscription Trend</h5>
            </div>
            <div class="card-body">
                <canvas id="subscriptionChart" style="height: 300px;"></canvas>
            </div>
        </div>
    </div>
</div>

<!-- Data Table -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h5>Daily CRBT MIS Data</h5>
            </div>
            <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>New Subscribers</th>
                        <th>Total Unsubscriptions</th>
                        <th>Active Subscribers</th>
                        <th>Tone Downloads</th>
                    </tr>
                </thead>
                        <tbody id="dailyMisBody">
                            <tr><td colspan="5" class="text-center">Loading...</td></tr>
                </tbody>
            </table>
</div>

                <!-- Pagination -->
                <nav aria-label="Daily MIS pagination" class="mt-3">
                    <ul class="pagination justify-content-center" id="dailyMisPagination">
                        <!-- Pagination will be generated by JavaScript -->
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        console.log('DOM Content Loaded');
        let subscriptionChart;
        let currentPage = 1;
        let totalPages = 1;
        let perPage = 10;
        
        // Test if elements exist
        console.log('Start date element:', document.getElementById('startDate'));
        console.log('End date element:', document.getElementById('endDate'));
        console.log('Apply filter button:', document.getElementById('applyFilter'));
        
        // Set default dates
        const today = new Date();
        const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
        document.getElementById('startDate').value = lastMonth.toISOString().split('T')[0];
        document.getElementById('endDate').value = today.toISOString().split('T')[0];
        
        // Test Chart.js
        console.log('Chart.js available:', typeof Chart !== 'undefined');

        function initCharts(labels = [], subs = []) {
        const subscriptionCtx = document.getElementById('subscriptionChart').getContext('2d');

            if (subscriptionChart) subscriptionChart.destroy();

            subscriptionChart = new Chart(subscriptionCtx, {
            type: 'line',
                data: { labels, datasets: [{ label: 'Subscriptions', data: subs, borderColor: 'rgb(75, 192, 192)', tension: 0.1 }] },
                options: { responsive: true, maintainAspectRatio: false }
            });
        }

        async function fetchDailyMIS(page = 1) {
            console.log('fetchDailyMIS called with page:', page);
            currentPage = page;
            const params = new URLSearchParams();
            const s = document.getElementById('startDate').value;
            const e = document.getElementById('endDate').value;
            console.log('Start date:', s, 'End date:', e);
            
            if (s) params.append('start_date', s);
            if (e) params.append('end_date', e);
            params.append('page', page);
            params.append('per_page', perPage);

            const url = `/api/crbt/daily-mis?${params.toString()}`;
            console.log('Fetching URL:', url);
                const tbody = document.getElementById('dailyMisBody');
            tbody.innerHTML = '<tr><td colspan="5" class="text-center">Loading...</td></tr>';

            try {
                const res = await fetch(url);
                const json = await res.json();
                const rows = Array.isArray(json.data) ? json.data : [];
                const pagination = json.pagination || {};

                console.log('Daily MIS API Response:', json);
                console.log('Rows count:', rows.length);
                console.log('Pagination:', pagination);
                
                // Update pagination info
                totalPages = pagination.last_page || 1;
                currentPage = pagination.current_page || 1;

                if (rows.length === 0) {
                    tbody.innerHTML = '<tr><td colspan="5" class="text-center">No data</td></tr>';
                    
                    // Update summary cards to show 0 when no data
                    document.getElementById('totalSubscriptions').querySelector('span').textContent = '0';
                    document.getElementById('totalUnsubscriptions').querySelector('span').textContent = '0';
                    document.getElementById('activeSubscribers').querySelector('span').textContent = '0';
                    
                    initCharts();
                    generatePagination(); // Generate pagination even if no data
                    return;
                }

                const labels = [];
                const subs = [];
                // Track latest (most recent date) values instead of sums
                let latestSubs = 0, latestUnsubs = 0, latestActive = 0;
                let latestDate = null;
                tbody.innerHTML = '';

                        rows.forEach(r => {
                            const date = r.date || '';
                            // Map CRBT data structure to expected fields
                            const subsCount = Number(r.activeNrml || 0); // New subscriptions (daily activations)
                            const unsubsCount = Number(r.vchurnNrml || 0); // Unsubscriptions (daily deactivations)
                            const activeCount = Number(r.activeBase || 0); // Active subscribers (total active base)
                            const toneDownloads = Number(r.VsmsSuccess || 0); // Tone downloads
                            
                            console.log('Processing row:', { date, subsCount, unsubsCount, activeCount, toneDownloads });
                            
                            labels.push(date);
                            subs.push(subsCount);

                            // Determine if this row is the latest by date
                            if (!latestDate || new Date(date) > new Date(latestDate)) {
                                latestDate = date;
                                latestSubs = subsCount;
                                latestUnsubs = unsubsCount;
                                latestActive = activeCount;
                            }
                            
                            tbody.insertAdjacentHTML('beforeend', `
                                <tr>
                                    <td>${date}</td>
                                    <td>${subsCount.toLocaleString()}</td>
                                    <td>${unsubsCount.toLocaleString()}</td>
                                    <td>${activeCount.toLocaleString()}</td>
                                    <td>${toneDownloads.toLocaleString()}</td>
                                </tr>
                            `);
                        });

                // Update summary cards using latest base counts (most recent date)
                document.getElementById('totalSubscriptions').querySelector('span').textContent = Number(latestSubs).toLocaleString();
                document.getElementById('totalUnsubscriptions').querySelector('span').textContent = Number(latestUnsubs).toLocaleString();
                document.getElementById('activeSubscribers').querySelector('span').textContent = Number(latestActive).toLocaleString();

                // Generate pagination controls
                generatePagination();

                initCharts(labels, subs);
            } catch (e) {
                tbody.innerHTML = `<tr><td colspan="5" class="text-danger text-center">Error loading data</td></tr>`;
                initCharts();
            }
        }

        function generatePagination() {
            const paginationContainer = document.getElementById('dailyMisPagination');
            if (!paginationContainer) return;

            let paginationHTML = '';

            // Previous button
            if (currentPage > 1) {
                paginationHTML += `<li class="page-item"><a class="page-link" href="#" data-page="${currentPage - 1}">Previous</a></li>`;
            } else {
                paginationHTML += `<li class="page-item disabled"><span class="page-link">Previous</span></li>`;
            }

            // Page numbers
            const startPage = Math.max(1, currentPage - 2);
            const endPage = Math.min(totalPages, currentPage + 2);

            for (let i = startPage; i <= endPage; i++) {
                if (i === currentPage) {
                    paginationHTML += `<li class="page-item active"><span class="page-link">${i}</span></li>`;
                } else {
                    paginationHTML += `<li class="page-item"><a class="page-link" href="#" data-page="${i}">${i}</a></li>`;
                }
            }

            // Next button
            if (currentPage < totalPages) {
                paginationHTML += `<li class="page-item"><a class="page-link" href="#" data-page="${currentPage + 1}">Next</a></li>`;
            } else {
                paginationHTML += `<li class="page-item disabled"><span class="page-link">Next</span></li>`;
            }

            paginationContainer.innerHTML = paginationHTML;

            // Add event listeners to pagination links
            paginationContainer.querySelectorAll('a[data-page]').forEach(link => {
                link.addEventListener('click', function(e) {
                    e.preventDefault();
                    const page = parseInt(this.getAttribute('data-page'));
                    fetchDailyMIS(page);
                });
            });
        }

        document.getElementById('applyFilter').addEventListener('click', function() {
            console.log('Apply Filter button clicked');
            fetchDailyMIS(1); // Reset to first page when filtering
        });
        
        
        console.log('Initial data load');
        fetchDailyMIS();
    });
</script>
@endpush 
@endsection